<?php
// $Id$

/**
 * Implementation of hook_help().
 */
function bot_twitter_help($path, $arg) {
  switch ($path) {
    case 'irc:features':
      return array(t('Twitter'));
    case 'irc:features#twitter':
      return t('Post a Twitter message with ".twitter Just landed in Detroit #amc09"');
  }
}

/**
 * Harvest related Twitter feeds.
 */
function bot_twitter_irc_bot_cron_fastest() {
  $feeds = bot_twitter_get_feeds();
  while ($feed = db_fetch_object($feeds)) {
    if ($channel = variable_get('bot_twitter_channel_' . $feed->fid, '')) {
      $items = db_query('SELECT a.iid, a.fid, a.link, a.title FROM {aggregator_item} a LEFT JOIN {bot_twitter} t ON a.iid = t.iid WHERE a.fid = %d AND t.iid IS NULL ORDER BY a.timestamp asc LIMIT %d', $feed->fid, variable_get('bot_twitter_limit', 1));
      while ($item = db_fetch_object($items)) {
        $link = explode('/', $item->link);
        bot_message($channel, '<' . $link[3] . '> ' . $item->title . ' ' . $item->link);
        drupal_write_record('bot_twitter', $item);
        // Follow the author, so she/he has a better chance of seeing any replies made via IRC.
        bot_twitter_follow($link[3]);
      }
    }
  }
}

/**
 * Implementation of hook_irc_msg_channel().
 */
function bot_twitter_irc_msg_channel($data, $from_query = FALSE) {
  if (preg_match('/^\.twitter (.*)/s', $data->message, $matches)) {
    $to = $from_query ? $data->nick : $data->channel;
    if ($status = bot_twitter_status('<' . $data->nick . '> ' . $matches[1])) {
      bot_message($to, $data->nick . ': ' . 'http://twitter.com/' . $status->user->screen_name . '/statuses/' . $status->id);
    }
  }
}

/**
 * All responses are available via a query.
 */
function bot_twitter_irc_msg_query($data) {
  bot_twitter_irc_msg_channel($data, TRUE);
}

/**
 * Implementation of hook_menu().
 */
function bot_twitter_menu() {
  $items['admin/settings/bot/twitter'] = array(
    'access arguments'  => array('administer bot'),
    'description'       => 'Configure Bot Twitter settings.',
    'page callback'     => 'drupal_get_form',
    'page arguments'    => array('bot_twitter_settings'),
    'title'             => 'Bot Twitter',
  );
  return $items;
}

/**
 * Build the settings form.
 */
function bot_twitter_settings() {
  $feeds = bot_twitter_get_feeds();
  $channels = preg_split('/\s*,\s*/', variable_get('bot_channels', '#test'));
  $options = array('' => t('None'));
  foreach ($channels as $channel) {
    list($channel) = explode(' ', $channel);
    $options[$channel] = $channel;
  }
  while ($feed = db_fetch_object($feeds)) {
    $form['bot_twitter_channel_' . $feed->fid] = array(
      '#title'         => t('IRC channel for feed %title', array('%title' => $feed->title)),
      '#description'   => t('Select an IRC channel to which messages from feed %url will be relayed.', array('%url' => $feed->url)),
      '#type'          => 'select',
      '#options'       => $options,
      '#default_value' => variable_get('bot_twitter_channel_' . $feed->fid, ''),
    );
  }
  $form['bot_twitter_limit'] = array(
    '#title'         => t('Message limit'),
    '#description'   => t('Maximum number of tweets to relay to IRC every 15 seconds. The default <em>1</em> is highly recommended to avoid channel flooding. For very active feeds, a slightly larger limit may be required.'),
    '#type'          => 'textfield',
    '#size'          => 10,
    '#default_value' => variable_get('bot_twitter_limit', 1),
  );
  $form['bot_twitter_username'] = array(
    '#title'         => t('Twitter username'),
    '#description'   => t('Enter your Twitter username.'),
    '#type'          => 'textfield',
    '#default_value' => variable_get('bot_twitter_username', ''),
  );
  $form['bot_twitter_password'] = array(
    '#title'         => t('Twitter password'),
    '#description'   => t('Enter your Twitter password.'),
    '#type'          => 'textfield',
    '#default_value' => variable_get('bot_twitter_password', ''),
  );
  return system_settings_form($form);
}

/**
 * Get all search.twitter.com feeds from Aggregator module.
 */
function bot_twitter_get_feeds() {
  return db_query("SELECT fid, title, url FROM {aggregator_feed} WHERE url LIKE '%s'", 'http://search.twitter.com/search.atom%');
}

/**
 * Follow a Twitter user.
 */
function bot_twitter_follow($username) {
  static $users = array();
  // We only try to follow each user once per bot execution.
  if (!isset($users[$username])) {
    try {
      $twitter = bot_twitter_factory();
      $user = $twitter->users->show($username);
      if (!$user->following) {
        $twitter->friendships->create($username);
      }
    }
    catch (Services_Twitter_Exception $e) {
      bot_twitter_exception($e);
    }
    $users[$username] = TRUE;
  }
}

/**
 * Update Twitter status.
 */
function bot_twitter_status($status) {
  try {
    $twitter = bot_twitter_factory();
    return $twitter->statuses->update($status);
  }
  catch (Services_Twitter_Exception $e) {
    bot_twitter_exception($e);
  }
}

/**
 * Return a Services_Twitter object.
 */
function bot_twitter_factory() {
  static $twitter;
  if (!isset($twitter)) {
    include_once('Services/Twitter.php');
    $twitter = new Services_Twitter(variable_get('bot_twitter_username', ''), variable_get('bot_twitter_password', ''));
  }
  return $twitter;
}

/**
 * Log a Services_Twitter_Exception.
 */
function bot_twitter_exception($e) {
  watchdog('bot_twitter', 'Exception: %message', array('%message' => $e->getMessage()), WATCHDOG_WARNING);
}

/**
 * Implementation of hook_form_FORM_ID_alter().
 */
function bot_twitter_form_aggregator_form_feed_alter(&$form, &$form_state) {
  $form['refresh']['#options'][0] = t('0 sec');
}

/**
 * Implementation of hook_cron().
 */
function bot_twitter_cron() {
  // Delete items that have been purged from the aggregator_item table.
  db_query('DELETE t FROM {bot_twitter} t LEFT JOIN {aggregator_item} a ON t.iid = a.iid WHERE a.iid IS NULL');
}
