<?php
// $Id: actions_permissions.module,v 1.1.2.2 2009/05/10 06:47:43 kratib Exp $

/**
 * Implementation of hook_perm().
 */
function actions_permissions_perm() {
  $perms = array();
  $actions = actions_list() + _actions_permissions_get_custom_actions();
  foreach ($actions as $callback => $action) {
    $perms[] = 'execute ' . $action['description'] . ' ('. $callback . ')';
  }
  module_load_include('inc', 'node', 'node.admin');
  foreach (array('node', 'user') as $type) {
    foreach (module_invoke_all($type .'_operations') as $operation) {
      if (is_array($operation['label']) || empty($operation['callback'])) continue;
      $perms[] = 'execute ' . $operation['label'] . ' ('. $operation['callback'] . ')';
    }
  }
  return $perms;
}

function _actions_permissions_get_custom_actions() {
  $actions = array();
  $static_actions = actions_list();
  $result = db_query("SELECT * FROM {actions} WHERE parameters > ''");
  while ($action = db_fetch_object($result)) {
    $actions[$action->aid] = array(
      'description' => $action->description,
      'type' => $action->type,
      'configurable' => FALSE,
      'parameters' => unserialize($action->parameters),
    );
    $actions[$action->aid]['behavior'] = isset($static_actions[$action->callback]['behavior']) ? $static_actions[$action->callback]['behavior'] : null;
  }
  return $actions;
}

