<?php
// $Id: sms_blast.module,v 1.2.2.1 2008/10/09 17:26:24 diggersf Exp $

/**
 * @file
 * Allows bulk text messages to be sent to registered users.
 */

/**
 * Implementation of hook_perm().
 */
function sms_blast_perm() {
  return array('send sms blasts');
}

/**
 * Implementation of hook_menu().
 */
function sms_blast_menu() {
  $items['sms_blast'] = array(
    'title'            => 'SMS Blast',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('sms_blast_form'),
    'access arguments' => array('send sms blasts'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Display the sms blast form
 */
function sms_blast_form() {
  $form['message'] = array(
    '#type' => 'textarea',
    '#title' => t('Message'),
    '#cols' => 60,
    '#rows' => 5,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Send'),
  );

  return $form;
}

/**
 * Submit handler for the sms blast form
 */
function sms_blast_form_submit(&$form, $form_state) {
  $result = db_query("SELECT uid FROM {sms_user} WHERE status = 2");
  while ($row = db_fetch_array($result)) {
    $users[] = $row;
  }

  foreach ($users as $user) {
    sms_user_send($user['uid'], $form_state['values']['message']);
  }
  drupal_set_message(t('The message was sent to %count users.', array('%count' => count($users))));
}
