<?php
// $Id: sms_blast.module,v 1.2 2008/07/30 19:42:56 diggersf Exp $

/**
 * @file
 * Allows bulk text messages to be sent to registered users.
 */

/**
 * Implementation of hook_menu().
 */
function sms_blast_menu($may_cache) {
  $items = array();

  if ($may_cache) {
    $items[] = array(
      'path' => 'sms_blast',
      'title' => t('SMS Blast'),
      'callback' => 'drupal_get_form',
      'callback arguments' => array('sms_blast_form'),
      'access' => user_access('send sms blasts'),
      'type' => MENU_NORMAL_ITEM,
    );  
  }
  
  return $items;
}

/**
 * Implementation of hook_perm().
 */
function sms_blast_perm() {
  return array('send sms blasts');
}

function sms_blast_form() {
  $form['message'] = array(
    '#type' => 'textarea',
    '#title' => t('Message'),
    '#cols' => 60,
    '#rows' => 5,
  );
  
  $form['submit'] = array(
    '#type' => 'submit', 
    '#value' => t('Send'),
  );
  
  return $form;
}

function sms_blast_form_submit($form_id, $form_values) {
  $result = db_query("SELECT uid FROM {users} WHERE uid <> 0");
  while ($row = db_fetch_array($result)) {
    $users[] = $row;
  }
  
  foreach ($users as $user) {
    $this_user = user_load(array('uid' => $user['uid']));
    if ($this_user->sms_user[0]['status'] == 2) {
      sms_send($this_user->sms_user[0]['number'], $form_values['message'], $this_user->sms_user[0]['gateway']);
    }
  }
}