<?php

/**
 * @file
 *   Vozmob organic group content type and settings module file.
 */

// Adds files maintained by features module.
include_once('vozmob_og.features.inc');

/**
 * Implementaion of hook_menu_alter().
 *
 * Adds access control to organic groups moderation view.
 *
 * Requires weight of module > 10 (of views). Could do something cool with
 * ctools pagemanager? Or could make our own menu item to render the view?
 */
function vozmob_og_menu_alter(&$items) {
  $items['node/%views_arg/moderation']['access callback'] = 'vozmob_og_moderation_access';
  $items['node/%views_arg/moderation']['access arguments'] = array(1);
}

/**
 * Menu access callback.
 *
 * node/%views_arg/moderation
 */
function vozmob_og_moderation_access($nid) {
  $node = node_load($nid);
  if (! og_is_group_admin($node)) {
    // not able to admin the group
    return FALSE;
  }
  $moderated = flag_get_flag('moderated_group');
  if (empty($moderated)) {
    //flag moderate_group missing!
    return FALSE;
  }
  if (! $moderated->is_flagged($nid)) {
    // this group isn't moderated
    return FALSE;
  }
  
  return TRUE;
}
function vozmob_og_link_alter(&$links, $node) {
  global $user;

  // Remove normal node links for group nodes and add group admin links instead.
  if ($node->type == 'group') {
    $links = array(); 
    if (node_access('update', $node, $user)) {
      $links['og_members'] = array(
        'title' => t('View Members'),
        'href' => "og/users/{$node->nid}",
        'attributes' => array('class' => 'og-memebers-link', 'title' => t('View memebers of ') . $node->title),
      );
      $links['og_add_members'] = array(
        'title' => t('Add Members'),
        'href' => "og/users/{$node->nid}/add_user",
        'attributes' => array('class' => 'og-memebers-link', 'title' => t('View memebers of ') . $node->title),
        'query' => 'destination=node/'. $node->nid,
      );
    }
  }
}