<?php
// $Id$

// CURRENTLY SUPPORTED:
// 'txt.att.net' => t('AT&T/Cingular'),
// 'mobile.celloneusa.com' => t('CellularOne'),
// 'cwemail.com' => t('Centennial Wireless'),
// 'sms.mycricket.com' => t('Cricket'),
// 'messaging.sprintpcs.com' => t('Helio'),
// 'page.nextel.com' => t('Nextel'),
// 'qwestmp.com' => t('Qwest'),
// 'messaging.sprintpcs.com' => t('Sprint'),
// 'tmomail.net' => t('T-Mobile'),
// 'vmobl.com' => t('Virgin Mobile'),
// 'vtext.com' => t('Verizon'),

// TO BE SUPPORTED:
// @mms.att.net are                                                                                                          
// @myboostmobile.com                                                                                                                                                               
// @messaging.nextel.com                                                                                                                                                            
// @mymetropcs.com

/**
 * Implementation of hook_mailsave_clean().
 * Attempt to match sender to a phone number stored by sms_user module.
 * If no match found and sender is a recognized SMS email gateway, 
 * create a user account.
 */
function sms_mailsave_mailsave_clean(&$node, $result, $i, $header, $mailbox) {
  if (!$node->uid) {
    list($from_address, $from_name) = mailhandler_get_fromaddress($header, $mailbox);
    $from = explode('@', $from_address);
    $sms_message['from'] = $from[0];
    sms_user_sms_receive($node, $sms_message);
    $sms_email_gateway_providers = sms_email_gateway_sms_email_gateway_providers();
    if (!$node->uid && isset($sms_email_gateway_providers[$from[1]])) {
      $user = user_save(NULL, array(
        'name' => implode('-', array(dechex(mt_rand()), dechex(mt_rand()))),
        'pass' => dechex(mt_rand()) . dechex(mt_rand()),
        'mail' => $from_address,
        'roles' => drupal_map_assoc(array(3)),
        'status' => 1,
        'sms_user' => array(array('number' => sms_formatter($from[0]), 'status' => 1, 'gateway' => array('carrier' => $from[1]))),
      ));
      $node->uid = $user->uid;
    }
    if ($node->uid) {
      mailhandler_switch_user($node->uid);
    }
  }
}
