<?php
/**
 * @file
 * MMS Messsaging using SMS Framework. Messaging method plug-in
 */

/**
 * Implementation of hook_messaging().
 */
function messaging_mms_messaging($op = 'info') {
  switch($op) {
    case 'send methods':
      $info['mms'] = array(
        'title' => 'SMS Framework E-mail Gateway',
        'name' => t('MMS'),
        'group' => 'mms', // Class of send method
        'type' => MESSAGING_TYPE_SEND,
        'glue' => '<br>', // don't use <br/> nor <br /> for maximum HTML email client compatibility
        'footer' => '<br><br>--',  // Separator for message footer
        'description' => t('Send MMS using SMS Framework E-mail Gateway.'),
        'send callback' => 'messaging_mime_mail_send_msg',  // Sending callback
        'destination callback' => 'messaging_mms_user_destination',
      );
      return $info;  
  }
}

/**
 * Map user account to MMS destination (phone number)
 */
function messaging_mms_user_destination($account, $message) {
  // Check for active mobile infomation. Simply return it so that the send
  // callback has a destination array and access everything.
  if (!empty($account->sms_user) && $account->sms_user['status'] == 2 && !empty($account->sms_user['number']) && !empty($account->sms_user['gateway']['carrier'])) {
    return $account->sms_user['number'] . '@' . $account->sms_user['gateway']['carrier'];
  }
}

/**
 * Implementation of hook_disable()
 */
function messaging_mms_disable() {
  messaging_method_disable('mms');
}
