<?php
// $Id: location_taxonomy.install,v 1.1.2.1 2009/04/03 18:37:04 bdragon Exp $

/**
 * @file
 * Install / uninstall routines for location_taxonomy.
 */

function location_taxonomy_uninstall() {
  // @@@ Delete data?

  // Delete vocabulary location settings.
  $result = db_query("SELECT name FROM {variable} WHERE name LIKE 'location_taxonomy_%'");
  while ($row = db_fetch_object($result)) {
    variable_del($row->name);
  }
}
