<?php
// $Id: favorite_services.module,v 1.1.2.2 2009/08/14 00:36:27 robloach Exp $

/**
 * @file
 * Provide the bookmarking support for various browser
 */
function favorite_services_service_links() {
  $links['favorite'] = array(
    'name' => 'Favorite',
    'description' => t('Add this page in your favorites'),
    'link' => url('', array('absolute' => TRUE, 'query' => '<encoded-url>#<encoded-title>')),
    'attributes' => array('class' => 'service_links_favorite', 'style' => 'display:none;'),
    'javascript' => drupal_get_path('module', 'service_links') .'/js/favorite_services.js',
  );
  return $links;
}
