<?php

// $Id: mm_auto_run.module,v 1.1.2.2.2.6 2010/02/22 21:31:19 arthuregg Exp $


/**
 * @FILE this provides auto run for specific
 *       configurations from media mover
 */


/* ********************************************** */
/* DRUPAL HOOKS                                   */
/* ********************************************** */


/**
 * Implementation of hook_menu().
 *
 * @return array
 */
function mm_auto_run_menu() {
  $items = array();
  $items['admin/build/media_mover/settings/mm_auto_run'] = array(
    'title' => 'Auto Run',
    '#description' => t('Configure automatically run Media Mover configurations.'),
    'access arguments' => array('administer media_mover'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mm_auto_run_settings_form'),
    'type' => MENU_LOCAL_TASK,
  );
  return $items;
}


/**
 * Implementation of hook_nodeapi()
 *
 * @param object $node
 * @param string $op
 * @param string $a3
 * @param string $a4
 */
function mm_auto_run_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  // we only run on update or insert
  if ($op == 'insert' || $op == 'update') {
    // get the list of configurations
    if ($configurations = variable_get('mm_auto_run_configs', false)) {
      // run each configuration that is enabled
      $has_run = array();
      foreach ($configurations as $cid => $enabled) {
        if ($enabled && ! in_array($cid, $has_run)) {
          $config = media_mover_api_get_configuration($cid);
          $has_run[$cid] = true;
          // run the media mover configuration on this node
          media_mover_api_run_config($config, true, $node->nid);
        }
      }
    }
  }
}


/* ********************************************** */
/* INTERNAL FUNCTIONS                             */
/* ********************************************** */


/**
 * Builds the settings form, used on admin/settings/mm_auto_run and
 * admin/media_mover/settings
 *
 * @return array
 */
function mm_auto_run_settings_form() {
  // build some description information
  $form['auto_run'] = array(
    '#type' => 'fieldset',
    '#title' => t('Media Mover Auto Run'),
    '#description' => t('Select which Media Mover configurations you would like to run automatically when a user creates or updates a node. This will only work with configurations that harvest their data from nodes.'),
    '#collapsible' => true,
  );

  // get a list of all current MM configurations
  $configurations = media_mover_api_get_configurations();
  foreach ($configurations as $configuration) {
    $options[$configuration->cid] = '<strong>'. $configuration->name .'</strong><br />'. $configuration->description;
  }

  $form['auto_run']['mm_auto_run_configs'] = array(
    '#title' => t('Select the configurations to run'),
    '#type' => 'checkboxes',
    '#options' => $options,
    '#default_value' => variable_get('mm_auto_run_configs', array()),
  );

  return system_settings_form($form);
}