<?php
/**
 * @file Provides sample scripts that demonstrate the capabilities of the VoIP Drupal platform
 */ 

/**
 * Implementation of hook_voipscript_load_script()
 */
function vozmob_callin_voipscript_load_script($script_name, $params=NULL) {
  $script = _vozmob_callin_load_sample_scripts($script_name);
  return $script;
}

/**
 * Implementation of hook_voipscript_get_script_names()
 */
function vozmob_callin_voipscript_get_script_names() {
  return array('voipscript_vozmob_callin');
}

/*
 * Sample scripts that highlight VoIP Drupal capabilities
 */
function _vozmob_callin_load_sample_scripts($script_name) {
  if ($script_name == 'voipscript_vozmob_callin') {

  $script = new VoipScript('vozmob_callin');

  $script->addLabel('language_selection');
  $script->addSetLanguage('es');
  $text = "Para espanol, oprima el numero uno";
  $url = '';
  $timeout = 3;
  $end_key = '';
  $num_digits = 1;
  $script->addGetInput($text, $url, $timeout, $end_key, $num_digits);

  $script->addGotoIf('switch_to_spanish', "^%input_digits == '1'");
  $script->addSetLanguage('en');
  $script->addSet('msg', 'Please record your message after the beep.  When done, press the pound key.');
  $script->addGoto('start_recording');

  $script->addLabel('switch_to_spanish');
  $script->addSetLanguage('es');
  $script->addSet('msg', 'Graba tu mensaje despues del tono. Quando estiver listo, oprime el #.');
//TODO: translate the remaining sentences to Spanish using Drupal's locale functionality. the commands "say" and "get input" automatically call t() with the appropriate language;
  $script->addGoto('start_recording');
  
  $script->addLabel('start_recording');
  $script->addSay('%msg');
  $timeout = 5;
  $end_key = '#';
  $max_length = 20;
  $script->addRecord($timeout, $end_key, $max_length);

  $script->addGotoIf('no recording detected', '^%recording_duration == 0');

  $script->addSay('You said ');
  //$script->addPlay('%recording_url');

  $script->addLabel('accept menu');
  $text = "To accept this recording, press 1.  To record it once again, press 2. To hangup, press the pound key.";
  $url = '';
  $timeout = 5;
  $end_key = '';
  $num_digits = 1;
  $script->addGetInput($text, $url, $timeout, $end_key, $num_digits);

  $script->addGotoIf('accept recording', "^%input_digits == '1'");

  $script->addGotoIf('start_recording', "^%input_digits == '2'");

  $script->addGotoIf('end call', "^%input_digits == '#'");

  $script->addSay('Invalid input received. Please try again.');
  $script->addGoto('accept menu');

  $script->addLabel('accept recording');
  $script->addSet('uid', $vars['uid']);
  $script->addSet('name', $vars['name']);
  $script->addSet('number', $vars['number']);
  // Process recording.
  $script->addSay('About to start processing the recorded file.');
  $script->addSet('callback_result',
        '^_vozmob_callin_record_callback(%call_id, %recording_url, %recording_duration, %uid, %name, %number)');
  $script->addSay('The callback returned: %callback_result');
  $script->addGoto('end call');

  $script->addLabel('no input received');
  $script->addSay("No input received. Please try again.");
  $script->addGoto('start_recording');

  $script->addLabel('no recording detected');
  $script->addSay("No recording detected. Please try again.");
  $script->addGoto('start_recording');

  $script->addLabel('end call');
  $script->addSay('Bye bye.');
  $script->addHangup();
  }
  return $script;
}

/**
 * Callback function associated with the script vozmob_callin_record_script.
 * It is called whenever that script records a new entry from the user.
 */
function _vozmob_callin_record_callback($call_id, $recording_url, $recording_duration, $uid, $name, $number) {
watchdog('vozmob_callin', "in _vozmob_callin_record_callback($call_id, $recording_url, $recording_duration, $uid, $name, $number)");

  // Construct the new node object.
  $node = new stdClass();

  $node->title = "callin message from $number";
  $body = t("New callin message recorded with call_id: $call_id, recording_url: $recording_url, uid: $uid, name: $name, number: $number");
  $node->body = $body;
  $node->type = 'story';
  $node->created = time();
  $node->changed = $node->created;
  $node->status = 1;          // Published?
  $node->promote = 1;       // Display on front page?
  $node->sticky = 0;          // Display top of page?
  $node->format = 1;         // Filtered HTML?
  $node->uid = $uid;             //  Content owner uid (author)?
  $node->language = 'en';

  node_submit($node);
  node_save($node);

  return 'Success';
}
