<?php
// $Id$

/**
 * Return map of SMS gateways and corresponding MMS gateways.
 */
function mms_email_gateway_get_map() {
  return array(
    'mms.comcel.net' => 'comcel.com.co',
    'pm.sprint.com' => 'messaging.sprintpcs.com',
    'messaging.nextel.com' => 'page.nextel.com',
    'mms.tigo.com.co' => 'sms.tigo.com.co',
    'mms.att.net' => 'txt.att.net',
    'mypixmessages.com' => 'vtext.com',
    'vzwpix.com' => 'vtext.com',
    'pixmbl.com' => 'vmobl.com',
  );
}

/**
 * Rewrite an MMS gateway to its corresponding SMS gateway.
 */
function mms_email_gateway_rewrite_to_sms($gateway) {
  $gateways = mms_email_gateway_get_map();
  return isset($gateways[$gateway]) ? $gateways[$gateway] : $gateway;
}

/**
 * Rewrite an SMS gateway to its corresponding MMS gateway.
 */
function mms_email_gateway_rewrite_to_mms($gateway) {
  $gateways = array_flip(mms_email_gateway_get_map());
  return isset($gateways[$gateway]) ? $gateways[$gateway] : $gateway;
}

/**
 * Returns TRUE if given e-mail address is from an SMS or MMS gateway.
 */
function mms_email_gateway_is_carrier($mail) {
  static $carriers;
  if (!$carriers) {
    $carriers = sms_carriers() + mms_email_gateway_get_map();
  }
  $domain = preg_replace('/.*@/', '', $mail);
  return isset($carriers[$domain]);
}


/**
 * Implementation of hook_mailsave_clean().
 *
 * Add a file name extension to files that have a mime type but no extension.
 */
function mms_email_gateway_mailsave_clean(&$node, $result, $i, $header, $mailbox) {
  foreach ($node->mailsave_attachments as $key => $attachments) {
    if (pathinfo($attachments['filename'], PATHINFO_EXTENSION) === '') {
      if ($attachments['filemime'] == 'video/3gpp') {
        $node->mailsave_attachments[$key]['filename'] .= '.3gp';
      }
      if ($attachments['filemime'] == 'image/jpeg') {
        $node->mailsave_attachments[$key]['filename'] .= '.jpg';
      }
    }
  }
}
