<?php
// $Id$

/**
 * Return map of SMS gateways and corresponding MMS gateways.
 */
function mms_email_gateway_get_map() {
  return array(
    'messaging.sprintpcs.com' => 'pm.sprint.com',
    'page.nextel.com' => 'messaging.nextel.com',
    'sms.tigo.com.co' => 'mms.tigo.com.co',
    'txt.att.net' => 'mms.att.net',
    'vtext.com' => 'vzwpix.com',
  );
}

/**
 * Rewrite an MMS gateway to its corresponding SMS gateway.
 */
function mms_email_gateway_rewrite_to_sms($gateway) {
  $gateways = array_flip(mms_email_gateway_get_map());
  return isset($gateways[$gateway]) ? $gateways[$gateway] : $gateway;
}

/**
 * Rewrite an SMS gateway to its corresponding MMS gateway.
 */
function mms_email_gateway_rewrite_to_mms($gateway) {
  $gateways = mms_email_gateway_get_map();
  return isset($gateways[$gateway]) ? $gateways[$gateway] : $gateway;
}

/**
 * Implementation of hook_mailsave_clean().
 *
 * Add a file name extension to files that have a mime type but no extension.
 */
function mms_email_gateway_mailsave_clean(&$node, $result, $i, $header, $mailbox) {
  foreach ($node->mailsave_attachments as $key => $attachments) {
    if (pathinfo($attachments['filename'], PATHINFO_EXTENSION) === '') {
      if ($attachments['filemime'] == 'video/3gpp') {
        $node->mailsave_attachments[$key]['filename'] .= '.3gp';
      }
    }
  }
}
