<?php
// $Id: sms_email_gateway.module,v 1.3 2008/08/07 18:08:59 diggersf Exp $

function sms_email_gateway_gateway_info() {
  
  return array(
    'email' => array(
      'name' => 'E-mail',
      'identifier' => 'email',
      'send_form' => 'sms_email_gateway_send_form',
      'send' => 'sms_email_gateway_send',
    ),
  );
}

/**
 * Returns custom additions to be added to the send forms
 */
function sms_email_gateway_send_form($destination = NULL, $required = TRUE) {  
  $options = array();
  if (!$required) {
    $options[0] = '<'. t('none') .'>';
  }
  
  $providers = module_invoke_all('sms_email_gateway_providers');
  asort($providers);
  $options += $providers;
    
  $form['carrier'] = array(
    '#type' => 'select',
    '#title' => t('Carrier'),
    '#multiple' => FALSE,
    '#description' => t('Select your wireless carrier.'),
    '#options' => $options,
    '#default_value' => isset($destination->carrier) ? $destination->carrier : NULL,
    '#required' => $required,
  );
  
  return $form;
}

/**
 * Callback for sending messages.
 */
function sms_email_gateway_send($number, $message, $options) {
  $to = $number .'@'. $options['carrier'];
  $params['message'] = $message; 
  drupal_mail('sms_email_gateway', 'sms', $to, language_default(), $params);
}

/**
 * Implementation of hook_mail().
 */
function sms_email_gateway_mail($key, &$message, &$params) {
  $message['body'] = $params['message'];
  unset($message['params']['message']);
}

/**
 * Implementation of hook_sms_email_gateway_providers()
 */
function sms_email_gateway_sms_email_gateway_providers() {
  return array(
    'msg.acsalaska.com' => t('Alaska Communications Systems'),
    'message.alltel.com' => t('Alltel Wireless'),
    'txt.att.net' => t('AT&T/Cingular'),
    'mobile.celloneusa.com' => t('CellularOne'),
    'cwemail.com' => t('Centennial Wireless'),
    'sms.mycricket.com' => t('Cricket'),
    'messaging.sprintpcs.com' => t('Helio'),
    'page.nextel.com' => t('Nextel'),
    'qwestmp.com' => t('Qwest'),
    'messaging.sprintpcs.com' => t('Sprint'),
    'tmomail.net' => t('T-Mobile'),
    'vmobl.com' => t('Virgin Mobile'),
    'vtext.com' => t('Verizon'),
  );
}
