<?php
// $Id: bot_agotchi.install,v 1.1.2.1.2.1 2008/06/23 17:52:24 morbus Exp $

/**
 * Implementation of hook_uninstall().
 */
function bot_agotchi_uninstall() {
  variable_del('bot_agotchi_feeding_responses');
  variable_del('bot_agotchi_greeting_triggers');
  variable_del('bot_agotchi_greeting_randomness');
  variable_del('bot_agotchi_greeting_responses');
  variable_del('bot_agotchi_thankful_responses');
}
