<?php
// $Id$

/**
 * @file
 * VozMob custom support module.
 */

/**
 * Implementation of hook_views_api().
 */
function vozmob_support_views_api() {
  return array('api' => 2);
}

/**
 * Implementation of hook_form_alter().
 */
function vozmob_support_form_alter(&$form, $form_state, $form_id) {
  switch ($form_id) {
    case 'messaging_sendto_form':
      $form['sendto']['#description'] = t("Enter a recipient's mobile phone number, email address or user name.");
      $form['sendto']['#weight'] = -20;
      $gateway = sms_default_gateway();
      if (function_exists($gateway['send form'])) {
        $form['gateway']['#tree'] = TRUE;
        $form['gateway']['#weight'] = -10;
        $form['gateway'] = array_merge($gateway['send form']($required), $form['gateway']);
      }
      if (isset($form['gateway']['carrier']['#description'])) {
        $form['gateway']['carrier']['#description'] = t("Select the recipient's wireless carrier if sending to a phone number.");
      }
      break;
  }
}

/**
 * Implementation of hook_nodeapi().
 */
function vozmob_support_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  // Move the messaging_sendto form down to the bottom of the node.
  if ($op == 'view' && isset($node->content['messaging_sendto']['#weight'])) {
    $node->content['messaging_sendto']['#weight'] = 40;
  }
}

/**
 * Implementation of hook_mail_alter().
 */
function vozmob_support_mail_alter(&$message){
  if (!empty($message['from'])){
    $message['headers']['Return-Path'] = $message['from'];
  }
  // Add some temporary debugging :P
  watchdog('vozmob', '<pre>'.check_plain(print_r($message, TRUE)).'</pre>', NULL);
}
