<?php

/**
 * Implements hook_mailhandler().
 */
function mail2term_mailhandler($node, $result, $i, $header, $mailbox) {
  $local = strtok($header->toaddress, '@');
  $components = explode('+', $local);
  foreach ($components as $component) {
    $new_component = TRUE;
    $result = db_query(db_rewrite_sql("SELECT s.tid FROM {term_synonym} s INNER JOIN {term_data} t ON s.tid = t.tid INNER JOIN {vocabulary_node_types} v ON t.vid = v.vid WHERE s.name = '%s' AND v.type = '%s'", 't', 'tid'), $component, $node->type);
    while ($term = db_fetch_object($result)) {
      $new_component = FALSE;
      $node->taxonomy[$term->tid] = $term->tid;
    }
    $result = db_query(db_rewrite_sql("SELECT t.tid FROM {term_data} t INNER JOIN {vocabulary_node_types} v ON t.vid = v.vid WHERE t.name = '%s' AND v.type = '%s'", 't', 'tid'), $component, $node->type);
    while ($term = db_fetch_object($result)) {
      $new_component = FALSE;
      $node->taxonomy[$term->tid] = $term->tid;
    }
    if ($new_component) {
      $result = db_query(db_rewrite_sql("SELECT v.vid FROM {vocabulary} v INNER JOIN {vocabulary_node_types} n ON v.vid = n.vid WHERE n.type = '%s' and v.tags = %d", 'v', 'vid'), $node->type, 1);
      while ($vocabulary = db_fetch_object($result)) {
        $term = array('name' => $component, 'vid' => $vocabulary->vid);
        taxonomy_save_term($term);
        $node->taxonomy[$term['tid']] = $term['tid'];
      }
    }
  }
  return $node;
}
