<?php
// $Id$

/**
 * @file
 * Process slideshow-type messages containing IMAGE parts followed by TEXT parts.
 * The TEXT parts should serve as the image descriptions.
 */

/**
 * Implementation of hook_mailsave().
 */
function mailsave_to_textpart_mailsave($node, $result, $i, $header, $mailbox) {

  // Initialize variables.
  $image = FALSE;
  $text = FALSE;
  $mimepairs = array();

  // Find all TEXT parts which follow an IMAGE part.
  foreach ($node->mimeparts as $key => $mimepart) {
    $text = (strpos($mimepart->filemime, 'TEXT/') === 0 && $mimepart->filemime != 'TEXT/X-VCARD') ? TRUE : FALSE;
    if ($text && $image) {
      $mimepairs[] = array('image' => $key - 1, 'text' => $key);
    }
    $image = (strpos($mimepart->filemime, 'IMAGE/') === 0) ? TRUE : FALSE;
  }

  // This is site-specific code, using a 'field_image' field created in CCK.  
  foreach ($mimepairs as $mimepair) {
    foreach ($node->field_image as $index => $field_image) {
      if ($field_image['mimepart'] == $mimepair['image']) {
        $node->field_image[$index]['data']['description'] = $node->mimeparts[$mimepair['text']]->data;
        $node->field_image[$index]['data']['title'] = $node->mimeparts[$mimepair['text']]->data;
      }
    }
  }

  return $node;
}
