<?php
// $Id: sms_clickatell.module,v 1.3 2008/08/07 18:08:59 diggersf Exp $

function sms_clickatell_gateway_info() {
  $options['sms_clickatell_ssl'] = array(
    '#type' => 'checkbox',
    '#title' => t('Use SSL Encyption'),
    '#description' => t('Drupal\'s built-in HTTP client only supports SSL on PHP 4.3 compiled with OpenSSL.'),
    '#default_value' => variable_get('sms_clickatell_ssl', 0),
  );
  $options['sms_clickatell_api_id'] = array(
    '#type' => 'textfield',
    '#title' => t('API ID'),
    '#description' => t('Clickatell issues this number upon addition of an HTTP sub-product to your account.'),
    '#size' => 40,
    '#maxlength' => 255,
    '#default_value' => variable_get('sms_clickatell_api_id', ''),
  );
  $options['sms_clickatell_user'] = array(
    '#type' => 'textfield',
    '#title' => t('User'),
    '#description' => t('The username of your Clickatell account.'),
    '#size' => 40,
    '#maxlength' => 255,
    '#default_value' => variable_get('sms_clickatell_user', ''),
  );
  $options['sms_clickatell_password'] = array(
    '#type' => 'textfield',
    '#title' => t('Password'),
    '#description' => t('The current password on your Clickatell account.'),
    '#size' => 30,
    '#maxlength' => 64,
    '#default_value' => variable_get('sms_clickatell_password', ''),
  );
  
  return array(
    'clickatell' => array(
      'name' => 'Clickatell',
      'identifier' => 'clickatell',
      'options' => $options,
      'validate' => 'sms_clickatell_validate',
      'send' => 'sms_clickatell_send',
      'send_form' => 'sms_clickatell_send_form',
    ),
  );
}

/**
 * Validates the submission of the configuration form.
 */ 
function sms_clickatell_validate($form, &$form_state) {
  $result = sms_clickatell_command('auth', array(), $form_state['values']);
  $codes = sms_clickatell_error_codes();
  if ($result['status'] == 'ERR') {
    form_set_error('', t('A Clickatell gateway error occured: '. $codes[floor($result['code'])]));
  }
  variable_set('sms_clickatell_session_id_timestamp', 0);
}

/**
 * Returns custom additions to be added to the send forms
 */
function sms_clickatell_send_form() {
  $form['country'] = array(
    '#type' => 'select',
    '#title' => t('Country'),
    '#multiple' => FALSE,
    '#options' => sms_clickatell_country_codes(),
    '#default_value' => -1,
    // '#required' => TRUE,
  );
  
  return $form;
}

/**
 * Callback for sending messages.
 */
function sms_clickatell_send($number, $message, $options) {
  $number = $options['country'] . $number;
  $result = sms_clickatell_command('sendmsg', array('number' => $number, 'message' => $message));
}

function sms_clickatell_balance() {
  $result = sms_clickatell_command('getbalance');
  return $return['data'];
}

/**
 * Executes a command using the Clickatell API
 */
function sms_clickatell_command($command = 'auth', $data = array(), $config = NULL) {
  $gateway = sms_gateways('gateway', 'clickatell');
    
  if ($config == NULL) {
    $config = $gateway['configuration'];
  }
  
  if ($config['sms_clickatell_ssl']) {
    $scheme = 'https';
  }
  else {
    $scheme = 'http';
  }
  
  switch ($command) {
    case 'auth':
      $query = 'api_id='. $config['sms_clickatell_api_id'] .'&user='. $config['sms_clickatell_user'] .'&password='. $config['sms_clickatell_password'];
      break;
    case 'sendmsg':
      $query = 'session_id='. sms_clickatell_get_session_id() .'&to='. $data['number'] .'&text='. drupal_urlencode($data['message']);
      break;
    case 'getbalance':
      $query = 'session_id='. sms_clickatell_get_session_id();
      break;
  }

  // Run the command
  $result = drupal_http_request($scheme .'://api.clickatell.com/http/'. $command .'?'. $query);

  // Check for HTTP errors
  if ($result->error) {
    drupal_set_message(t('An error occured during the HTTP request: '. $result->error), 'error');
    return 0;
  }
  
  if ($result->data) {
    switch ($command) {
      case 'auth':
        list($response['status'], $response['data']) = explode(': ', $result->data);
        $response['code'] = drupal_substr($response['data'], 0, 3);
        $response['message'] = drupal_substr($response['data'], 5, drupal_strlen($response['data']) - 1);
        break;
      case 'sendmsg':
        $response = explode(': ', $result->data);
        break;
      case 'getbalance':
        list($response['status'], $response['data']) = explode(': ', $result->data);
        break;
    }
    
    return $response;
  }
}

function sms_clickatell_get_session_id() {
  if (variable_get('sms_clickatell_session_id_timestamp', 0) < strtotime('-10 mins')) {
    if ($result = sms_clickatell_command()) {
      if ($result['status'] == 'OK') {
        variable_set('sms_clickatell_session_id', $result['data']);
        variable_set('sms_clickatell_session_id_timestamp', time());
        watchdog('sms', 'Clickatell session ID refreshed: %data', array('%data' => $result['data']));
      }
    }
  }
  
  return variable_get('sms_clickatell_session_id', 0);
}

/**
 * Returns an array of error codes and messages that are generated by the Clickatell gateway
 */
function sms_clickatell_error_codes() {
  return array(
    001 => 'Authentication failed', 002 => 'Unknown username or password', 003 => 'Session ID expired',
    004 => 'Account frozen', 005 => 'Missing session ID', 007 => 'IP Lockdown violation',
    101 => 'Invalid or missing parameters', 102 => 'Invalid user data header',
    103 => 'Unknown API message ID', 104 => 'Unknown client message ID',
    105 => 'Invalid destination address', 106 => 'Invalid source address', 107 => 'Empty message',
    108 => 'Invalid or missing API ID', 109 => 'Missing message ID',
    110 => 'Error with email message',
    111 => 'Invalid protocol', 112 => 'Invalid message type',
    113 => 'Maximum message parts exceeded',
    114 => 'Cannot route message',
    115 => 'Message expired',
    116 => 'Invalid Unicode data', 120 => 'Invalid delivery time',
    201 => 'Invalid batch ID', 202 => 'No batch template',
    301 => 'No credit left', 302 => 'Max allowed credit',
  );
}

function sms_clickatell_country_codes() {
  return array(
    1 => 'United States',
  );
}