<?php
// $Id: sms_clickatell.module,v 1.7 2008/08/20 19:52:38 diggersf Exp $

/**
 * @file
 * Adds support for sending SMS messages using the Clickatell gateway.
 */

/**
 * Implementation of hook_gateway_info().
 */
function sms_clickatell_gateway_info() {
  return array(
    'clickatell' => array(
      'name' => 'Clickatell',
      'configure form' => 'sms_clickatell_admin_form',
      'send' => 'sms_clickatell_send',
      'send form' => 'sms_clickatell_send_form',
    ),
  );
}

function sms_clickatell_admin_form($configuration) {
  $form['sms_clickatell_ssl'] = array(
    '#type' => 'checkbox',
    '#title' => t('Use SSL Encyption'),
    '#description' => t('Drupal\'s built-in HTTP client only supports SSL on PHP 4.3 compiled with OpenSSL.'),
    '#default_value' => $configuration['sms_clickatell_ssl'],
  );
  $form['sms_clickatell_api_id'] = array(
    '#type' => 'textfield',
    '#title' => t('API ID'),
    '#description' => t('Clickatell issues this number upon addition of an HTTP sub-product to your account.'),
    '#size' => 40,
    '#maxlength' => 255,
    '#default_value' => $configuration['sms_clickatell_api_id'],
  );
  $form['sms_clickatell_user'] = array(
    '#type' => 'textfield',
    '#title' => t('User'),
    '#description' => t('The username of your Clickatell account.'),
    '#size' => 40,
    '#maxlength' => 255,
    '#default_value' => $configuration['sms_clickatell_user'],
  );
  $form['sms_clickatell_password'] = array(
    '#type' => 'textfield',
    '#title' => t('Password'),
    '#description' => t('The current password on your Clickatell account.'),
    '#size' => 30,
    '#maxlength' => 64,
    '#default_value' => $configuration['sms_clickatell_password'],
  );
  
  return $form;
}

/**
 * Validates the submission of the configuration form.
 */ 
function sms_clickatell_admin_form_validate($form, &$form_state) {
  $result = sms_clickatell_command('auth', array(), $form_state['values']);
  if (!$result['status']) {
    form_set_error('', t('A Clickatell gateway error occured: @error.', array('@error' => $result['message'])));
  }
  variable_set('sms_clickatell_session_id_timestamp', 0);
}

/**
 * Returns custom additions to be added to the send forms
 */
function sms_clickatell_send_form() {
  $form['country'] = array(
    '#type' => 'select',
    '#title' => t('Country'),
    '#multiple' => FALSE,
    '#options' => sms_clickatell_country_codes(),
    '#default_value' => -1,
  );
  
  return $form;
}

/**
 * Callback for sending messages.
 */
function sms_clickatell_send($number, $message, $options) {
  $number = $options['country'] . $number;
  return sms_clickatell_command('sendmsg', array('number' => $number, 'message' => $message));
}

function sms_clickatell_balance() {
  $result = sms_clickatell_command('getbalance');
  return $return['data'];
}

/**
 * Executes a command using the Clickatell API
 */
function sms_clickatell_command($command = 'auth', $data = array(), $config = NULL) {
  $gateway = sms_gateways('gateway', 'clickatell');
    
  if ($config == NULL) {
    $config = $gateway['configuration'];
  }
  
  if ($config['sms_clickatell_ssl']) {
    $scheme = 'https';
  }
  else {
    $scheme = 'http';
  }
  
  switch ($command) {
    case 'auth':
      $query = 'api_id='. $config['sms_clickatell_api_id'] .'&user='. $config['sms_clickatell_user'] .'&password='. $config['sms_clickatell_password'];
      break;
    case 'sendmsg':
      // Check if the message requires unicode handling
      if ($unicode_message = sms_clickatell_unicode($data['message'])) {
        $message = $unicode_message;
      }
      else {
        $message = drupal_urlencode($data['message']);
      }
      $query = 'session_id='. sms_clickatell_get_session_id() .'&to='. $data['number'] .'&text='. $message;
      break;
    case 'getbalance':
      $query = 'session_id='. sms_clickatell_get_session_id();
      break;
  }

  // Run the command
  $http_result = drupal_http_request($scheme .'://api.clickatell.com/http/'. $command .'?'. $query);

  // Check for HTTP errors
  if ($http_result->error) {
    return array('status' => FALSE, 'message' => 'An error occured during the HTTP request: @error', 'variables' => array('@error' => $http_result->error));
  }
  
  if ($http_result->data) {
    // Check for Clickatell errors
    if (strpos($http_result->data, 'ERR') !== FALSE) {
      $result = array('status' => FALSE, 'message' => $http_result->data);
    }
    else {
      $result = array('status' => TRUE, 'sid' => $sid);
    }
    switch ($command) {
      case 'auth':
        if ($result['status']) {
          // Add Clickatell session ID to result array.
          list($status, $sid) = explode(': ', $http_result->data);
          $result['sid'] = $sid;
        }
        break;
    }
  }
  return $result;
}

function sms_clickatell_get_session_id() {
  if (variable_get('sms_clickatell_session_id_timestamp', 0) < strtotime('-10 mins')) {
    if ($result = sms_clickatell_command()) {
      if ($result['status'] == TRUE) {
        variable_set('sms_clickatell_session_id', $result['sid']);
        variable_set('sms_clickatell_session_id_timestamp', time());
        watchdog('sms', 'Clickatell session ID refreshed: %data', array('%data' => $result['sid']));
      }
    }
  }
  
  return variable_get('sms_clickatell_session_id', 0);
}

/**
 * Returns an array of error codes and messages that are generated by the Clickatell gateway
 */
function sms_clickatell_error_codes() {
  return array(
    001 => 'Authentication failed', 002 => 'Unknown username or password', 003 => 'Session ID expired',
    004 => 'Account frozen', 005 => 'Missing session ID', 007 => 'IP Lockdown violation',
    101 => 'Invalid or missing parameters', 102 => 'Invalid user data header',
    103 => 'Unknown API message ID', 104 => 'Unknown client message ID',
    105 => 'Invalid destination address', 106 => 'Invalid source address', 107 => 'Empty message',
    108 => 'Invalid or missing API ID', 109 => 'Missing message ID',
    110 => 'Error with email message',
    111 => 'Invalid protocol', 112 => 'Invalid message type',
    113 => 'Maximum message parts exceeded',
    114 => 'Cannot route message',
    115 => 'Message expired',
    116 => 'Invalid Unicode data', 120 => 'Invalid delivery time',
    201 => 'Invalid batch ID', 202 => 'No batch template',
    301 => 'No credit left', 302 => 'Max allowed credit',
  );
}

function sms_clickatell_country_codes() {
  return array(
    1 => 'United States',
  );
}

/**
 * Converts a string to USC-2 encoding if neccessary.
 */
function sms_clickatell_unicode($message) {
  if (function_exists('iconv')) {
    $latin = @iconv('UTF-8', 'ISO-8859-1', $message);
    if (strcmp($latin, $message)) {
      $arr = unpack('H*hex', @iconv('UTF-8', 'UCS-2BE', $message));
      return strtoupper($arr['hex']) .'&unicode=1';
    }
  }
  return FALSE;
}