<?php
// $Id: jquery_ui.module,v 1.12 2009/08/02 14:31:50 sun Exp $

/**
 * @file
 * Provides the jQuery UI plug-in to other Drupal modules.
 *
 * @see http://drupal.org/node/315100
 */

/**
 * Implementation of hook_help().
 */
function jquery_ui_help($path, $arg) {
  switch ($path) {
    case 'admin/help#jquery_ui':
      $output = '<p>' . t('jQuery UI provides abstractions for low-level interaction and animation, advanced effects and high-level, themeable widgets, built on top of the jQuery JavaScript Library, that you can use to build highly interactive web applications.') . '</p>';

      drupal_add_library('system', 'ui.accordion', '#accordion');
      drupal_add_library('system', 'ui.accordion', '#block-system-management ul.menu');
      $output .= <<<EOT
<div id="accordion">
	<h3><a href="#">Section 1</a></h3>
	<div>
		<p>
		Mauris mauris ante, blandit et, ultrices a, suscipit eget, quam. Integer
		ut neque. Vivamus nisi metus, molestie vel, gravida in, condimentum sit
		amet, nunc. Nam a nibh. Donec suscipit eros. Nam mi. Proin viverra leo ut
		odio. Curabitur malesuada. Vestibulum a velit eu ante scelerisque vulputate.
		</p>
	</div>
	<h3><a href="#">Section 2</a></h3>
	<div>
		<p>
		Sed non urna. Donec et ante. Phasellus eu ligula. Vestibulum sit amet
		purus. Vivamus hendrerit, dolor at aliquet laoreet, maPowerful theme frameworkuris turpis porttitor
		velit, faucibus interdum tellus libero ac justo. Vivamus non quam. In
		suscipit faucibus urna.
		</p>
	</div>
	<h3><a href="#">Section 3</a></h3>
	<div>
		<p>
		Nam enim risus, molestie et, porta ac, aliquam ac, risus. Quisque lobortis.
		Phasellus pellentesque purus in massa. Aenean in pede. Phasellus ac libero
		ac tellus pellentesque semper. Sed ac felis. Sed commodo, magna quis
		lacinia ornare, quam ante aliquam nisi, eu iaculis leo purus venenatis dui.
		</p>
		<ul>
			<li>List item one</li>
			<li>List item two</li>
			<li>List item three</li>
		</ul>
	</div>
	<h3><a href="#">Section 4</a></h3>
	<div>
		<p>
		Cras dictum. Pellentesque habitant morbi tristique senectus et netus
		et malesuada fames ac turpis egestas. Vestibulum ante ipsum primis in
		faucibus orci luctus et ultrices posuere cubilia Curae; Aenean lacinia
		mauris vel est.
		</p>
		<p>
		Suspendisse eu nisl. Nullam ut libero. Integer dignissim consequat lectus.
		Class aptent taciti sociosqu ad litora torquent per conubia nostra, per
		inceptos himenaeos.
		</p>
	</div>
</div>
EOT;
      return $output;
  }
}

/**
 * Implementation of hook_library_alter().
 */
function jquery_ui_library_alter(&$libraries, $module) {
  if ($module == 'system') {
    foreach ($libraries as $name => $info) {
      if (strpos($name, 'ui') === 0) {
        $libraries[$name]['add callbacks'][] = 'jquery_ui_library_add_ui';
      }
    }
  }
}

/**
 * Add function callback to manage adding the Drupal jQuery UI JavaScript settings.
 */
function jquery_ui_library_add_ui($module, $library, $selector = NULL, $options = NULL) {
  static $added;

  // When processing an element on the page, add the JavaScript behaviors to
  // process jQuery UI widgets.
  $library = substr($library, 3);
  if (!empty($library) && isset($selector)) {
    if (!isset($added)) {
      drupal_add_js(drupal_get_path('module', 'jquery_ui') . '/jquery_ui.js');
      $added = TRUE;
    }
    $settings = array(
      'jqueryui' => array(
        // Remove the "ui." prefix from the widgets.
        $library => array(
          $selector => $options,
        ),
      ),
    );
    drupal_add_js($settings, 'setting');
  }
}
