<?php
// $Id: views_test.module,v 1.1.4.6 2010/07/10 06:09:56 dereine Exp $

/**
 * Implements hook_perm().
 */
function views_test_perm() {
  return array('views_test test permission');
}

/**
 * Implements hook_views_api().
 */
function views_test_views_api() {
  return array(
    'api' => 3.0,
  );
}

/**
 * Implements hook_views_data()
 */
function views_test_views_data() {
  return variable_get('views_test_views_data', array());
}

/**
 * Implements hook_views_plugins()
 */
function views_test_views_plugins() {
  return variable_get('views_test_views_plugins', array());
}
